# Generated by Django 3.1.5 on 2021-01-19 10:18

import RegistrationApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_no',
            field=models.IntegerField(default=904356923782, validators=[RegistrationApp.models.aadhar_check]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(default=6186065116, validators=[RegistrationApp.models.phone_check]),
        ),
    ]
