# Generated by Django 3.1.5 on 2021-01-19 10:24

import RegistrationApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0002_auto_20210119_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_no',
            field=models.IntegerField(default=0, validators=[RegistrationApp.models.aadhar_check]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(default=0, validators=[RegistrationApp.models.phone_check]),
        ),
    ]
