# Generated by Django 3.1.5 on 2021-01-20 08:24

import RegistrationApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0006_auto_20210120_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhar_no',
            field=models.CharField(default='000000000000', max_length=100, unique=True, validators=[RegistrationApp.models.aadhar_check]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
