# Generated by Django 3.1.5 on 2021-01-20 08:30

import RegistrationApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0007_auto_20210120_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_no',
            field=models.CharField(default='121212121212', max_length=100, unique=True, validators=[RegistrationApp.models.aadhar_check]),
        ),
    ]
