# Generated by Django 3.1.5 on 2021-01-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0010_auto_20210120_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Super', max_length=100),
        ),
    ]
