# Generated by Django 3.1.5 on 2021-01-20 09:36

import RegistrationApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0012_auto_20210120_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_no',
            field=models.CharField(default='000000000000', max_length=100, validators=[RegistrationApp.models.aadhar_check]),
        ),
    ]
