# Generated by Django 3.1.5 on 2021-01-23 10:48

import RegistrationApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0017_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to=RegistrationApp.models.user_directory_path),
        ),
    ]
