# Generated by Django 3.1.5 on 2021-01-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0018_auto_20210123_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='images/'),
        ),
    ]
