# Generated by Django 3.1.5 on 2021-01-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0022_auto_20210124_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_voting_officer',
            field=models.BooleanField(default=False),
        ),
    ]
