NANOSECONDS = 1
MICROSECONDS = 1000 * NANOSECONDS
MILLISECONDS=1000 * MICROSECONDS
SECONDS=100 * MILLISECONDS

MINE_RATE=4 * SECONDS

STARTING_BALANCE = 1

MINING_REWARD = 0
MINING_REWARD_INPUT = {'address': '*--official_mining_reward--*' }

BID_AMOUNT = 100
